// GitHub PR creation module for miniature-guacamole daemon
// WS-DAEMON-5: GitHub Client

import { execSync } from 'child_process';
import type { DaemonConfig, TicketData } from './types';

/**
 * Result of PR creation operation
 */
export interface PRResult {
  success: boolean;
  prUrl?: string;
  error?: string;
}

/**
 * Creates a draft pull request for the given ticket
 * AC-5.6: Creates draft PR with title '[KEY] summary' and body with Jira link + footer
 * AC-5.7: PR creation failure returns { success: false, error: string }
 * AC-5.8: Idempotent PR creation (returns existing PR URL if exists)
 * AC-5.10: GitHub operations use gh CLI via child_process.execSync
 */
export function createPR(
  ticketData: TicketData,
  branchName: string,
  config: DaemonConfig
): PRResult {
  const { key, summary, description, priority, labels } = ticketData;
  const { baseBranch, token } = config.github;
  const { host } = config.jira;

  // Build PR title
  const title = `[${key}] ${summary}`;

  // Build PR body
  const body = `**Jira Ticket:** [${key}](${host}/browse/${key})

## Description
${description}

## Priority
Priority: ${priority}

## Labels
${labels.join(', ')}

---
*Generated by miniature-guacamole daemon*`;

  const options = {
    cwd: process.cwd(),
    encoding: 'utf-8' as const,
    env: {
      ...process.env,
      GITHUB_TOKEN: token,
    },
  };

  try {
    // Create draft PR
    const command = `gh pr create --draft --head ${branchName} --base ${baseBranch} --title "${title}" --body "${body}"`;
    const output = execSync(command, options);
    const prUrl = output.toString().trim();

    return {
      success: true,
      prUrl,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);

    // Check if PR already exists (idempotent)
    if (errorMessage.includes('already exists')) {
      try {
        // Query existing PR
        const listCommand = `gh pr list --head ${branchName}`;
        const output = execSync(listCommand, options);
        const prUrl = output.toString().trim();

        return {
          success: true,
          prUrl,
        };
      } catch (listError) {
        const listErrorMessage = listError instanceof Error ? listError.message : String(listError);
        return {
          success: false,
          error: listErrorMessage,
        };
      }
    }

    // Return error for all other cases
    return {
      success: false,
      error: errorMessage,
    };
  }
}
