// GitHub PR creation module for miniature-guacamole daemon
// WS-DAEMON-5: GitHub Client

import { spawnSync } from 'child_process';
import type { DaemonConfig, TicketData } from './types';

/**
 * Result of PR creation operation
 */
export interface PRResult {
  success: boolean;
  prUrl?: string;
  error?: string;
}

/**
 * Creates a draft pull request for the given ticket
 * AC-5.6: Creates draft PR with title '[KEY] summary' and body with Jira link + footer
 * AC-5.7: PR creation failure returns { success: false, error: string }
 * AC-5.8: Idempotent PR creation (returns existing PR URL if exists)
 * AC-5.10: GitHub operations use gh CLI via child_process.spawnSync (argv array, no shell injection)
 */
export function createPR(
  ticketData: TicketData,
  branchName: string,
  config: DaemonConfig
): PRResult {
  const { key, summary, description, priority, labels, url } = ticketData;
  const { baseBranch } = config.github;
  // Note: token was removed from GitHubConfig; auth is now handled via gh CLI login
  const token = (config.github as Record<string, unknown>).token as string | undefined;

  // Build PR title
  const title = `[${key}] ${summary}`;

  // Build PR body — use ticket.url which is correct for all providers (Jira, Linear, GitHub)
  const body = `**Ticket:** [${key}](${url})

## Description
${description}

## Priority
Priority: ${priority}

## Labels
${labels.join(', ')}

---
*Generated by miniature-guacamole daemon*`;

  const spawnOptions = {
    cwd: process.cwd(),
    encoding: 'utf-8' as const,
    env: {
      ...process.env,
      GITHUB_TOKEN: token,
    },
  };

  try {
    // Create draft PR — argv array prevents shell injection
    const result = spawnSync('gh', [
      'pr', 'create', '--draft',
      '--head', branchName,
      '--base', baseBranch,
      '--title', title,
      '--body', body,
    ], spawnOptions);

    if (result.status !== 0) {
      const errorMessage = result.stderr?.trim() || 'PR creation failed';

      // Check if PR already exists (idempotent)
      if (errorMessage.includes('already exists')) {
        try {
          const listResult = spawnSync('gh', [
            'pr', 'list',
            '--head', branchName,
          ], spawnOptions);

          if (listResult.status !== 0) {
            throw new Error(listResult.stderr?.trim() || 'gh pr list failed');
          }

          const prUrl = listResult.stdout?.trim() ?? '';
          return { success: true, prUrl };
        } catch (listError) {
          const listErrorMessage = listError instanceof Error ? listError.message : String(listError);
          return { success: false, error: listErrorMessage };
        }
      }

      return { success: false, error: errorMessage };
    }

    const prUrl = result.stdout?.trim() ?? '';
    return { success: true, prUrl };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    return { success: false, error: errorMessage };
  }
}
