// Main pipeline coordinator for miniature-guacamole daemon
// WS-DAEMON-11: MG Orchestration Engine

import type { NormalizedTicket, TicketProvider } from './providers/types';
import type { DaemonConfig } from './types';
import type { WorkstreamPlan } from './planner';
import type { ExecutionResult } from './executor';
import type { ExecClaudeFn as PlannerExecClaudeFn } from './planner';
import type { ExecClaudeFn as ExecutorExecClaudeFn } from './executor';
import type { ExecClaudeFn as TriageExecClaudeFn, TriageResult, TriageConfig } from './triage';
import type { ExecSyncFn } from './worktree';
import type { PRResult } from './github';

import { execClaude as defaultExecClaude } from './claude';
import { planTicket as defaultPlanTicket } from './planner';
import { executeWorkstream as defaultExecuteWorkstream } from './executor';
import { triageTicket as defaultTriageTicket } from './triage';
import { createWorktree as defaultCreateWorktree, removeWorktree as defaultRemoveWorktree } from './worktree';
import { createPR as defaultCreatePR } from './github';
import { appendTriageLog } from './triage-log';
import { ConcurrencyLimiter } from './concurrency';
import { spawnSync } from 'child_process';
import { existsSync, statfsSync } from 'fs';
import { join } from 'path';

const STOP_SENTINEL = '.mg-daemon/STOP';
const MIN_FREE_DISK_BYTES = 5 * 1024 * 1024 * 1024; // 5 GB

/**
 * Check if the STOP sentinel file exists.
 * If .mg-daemon/STOP exists, the daemon should halt immediately.
 * This is an out-of-band emergency kill switch.
 */
export function shouldStop(): boolean {
  return existsSync(STOP_SENTINEL);
}

/**
 * Check if there is enough free disk space to create a worktree.
 * Returns false if free space is below 5 GB.
 */
export function hasSufficientDiskSpace(minBytes: number = MIN_FREE_DISK_BYTES): boolean {
  try {
    const stats = statfsSync('.');
    const freeBytes = stats.bfree * stats.bsize;
    return freeBytes >= minBytes;
  } catch {
    // If we can't check, assume it's OK (don't block on stat failures)
    return true;
  }
}

export interface OrchestratorConfig {
  provider: TicketProvider;
  config: DaemonConfig;
  tracker: {
    markProcessing: (key: string) => void;
    markComplete: (key: string, prUrl: string) => void;
    markFailed: (key: string, error: string) => void;
    getProcessedTickets: () => string[];
  };
  // Injectable dependencies for testing
  planTicket?: (
    ticket: NormalizedTicket,
    options: { timeout: number; dryRun: boolean },
    execClaudeFn: PlannerExecClaudeFn
  ) => Promise<WorkstreamPlan[]>;
  executeWorkstream?: (
    ws: WorkstreamPlan,
    ticket: NormalizedTicket,
    worktreePath: string,
    options: { timeout: number },
    execClaudeFn: ExecutorExecClaudeFn
  ) => Promise<ExecutionResult>;
  createWorktree?: (
    ticketId: string,
    summary: string,
    baseBranch: string,
    execSyncFn?: ExecSyncFn
  ) => { worktreePath: string; branchName: string };
  removeWorktree?: (worktreePath: string, execSyncFn?: ExecSyncFn) => void;
  createPR?: (...args: Parameters<typeof defaultCreatePR>) => PRResult;
  execClaude?: PlannerExecClaudeFn;
  triageTicket?: (
    ticket: NormalizedTicket,
    config: TriageConfig,
    execClaudeFn: TriageExecClaudeFn
  ) => Promise<TriageResult>;
}

export interface PipelineResult {
  ticketId: string;
  triageResult?: TriageResult;
  planned: WorkstreamPlan[];
  executed: ExecutionResult[];
  prUrl?: string;
  success: boolean;
  error?: string;
}

/**
 * Build PR description from ticket and execution results.
 */
function buildPRDescription(
  ticket: NormalizedTicket,
  planned: WorkstreamPlan[],
  executed: ExecutionResult[]
): string {
  const wsLines = planned.map((ws) => `- ${ws.name}`).join('\n');

  const resultLines = executed
    .map((r) => {
      const status = r.success ? 'PASS' : 'FAIL';
      const detail = r.error ? ` — ${r.error}` : '';
      return `- [${status}] ${r.workstream}${detail}`;
    })
    .join('\n');

  return `**Ticket:** [${ticket.id}](${ticket.url}) — ${ticket.title}

## Workstreams
${wsLines}

## Execution Results
${resultLines}

---
*Generated by miniature-guacamole daemon*`;
}

/**
 * Process a single ticket through the full pipeline:
 * 1. Transition ticket to In Progress
 * 2. Plan workstreams via Claude
 * 3. Create subtasks in tracker for each workstream
 * 4. Create worktree
 * 5. Execute each workstream via Claude
 * 6. Commit, push, create draft PR
 * 7. Link PR to ticket
 * 8. Transition ticket to In Review
 * 9. Clean up worktree
 */
export async function processTicket(
  ticket: NormalizedTicket,
  deps: OrchestratorConfig
): Promise<PipelineResult> {
  const orchestration = deps.config.orchestration ?? {
    claudeTimeout: 1_800_000,
    concurrency: 1,
    delayBetweenTicketsMs: 0,
    dryRun: false,
    errorBudget: 3,
  };
  const dryRun = orchestration.dryRun;
  const timeout = orchestration.claudeTimeout;
  const baseBranch = deps.config.github.baseBranch;

  const triageFn = deps.triageTicket ?? defaultTriageTicket;
  const planFn = deps.planTicket ?? defaultPlanTicket;
  const executeFn = deps.executeWorkstream ?? defaultExecuteWorkstream;
  const createWorktreeFn = deps.createWorktree ?? defaultCreateWorktree;
  const removeWorktreeFn = deps.removeWorktree ?? defaultRemoveWorktree;
  const createPRFn = deps.createPR ?? defaultCreatePR;
  const passthrough: PlannerExecClaudeFn = deps.execClaude ?? defaultExecClaude;

  // Mark as processing in tracker
  deps.tracker.markProcessing(ticket.id);

  // Step 0: Triage gate — assess ticket before planning
  const triageConfig: TriageConfig = deps.config.triage ?? {
    enabled: true,
    autoReject: false,
    maxTicketSizeChars: 10000,
  };

  const triageResult = await triageFn(ticket, triageConfig, passthrough);

  // Append to triage log (best-effort — never blocks pipeline)
  try {
    await appendTriageLog({
      ticketId: ticket.id,
      outcome: triageResult.outcome,
      reason: triageResult.reason,
      timestamp: new Date().toISOString(),
    }, '.');
  } catch {
    // Best-effort — swallow errors
  }

  if (triageResult.outcome !== 'GO') {
    // Post comment to ticket explaining the triage decision
    if (!dryRun) {
      try {
        const label = triageResult.outcome === 'REJECT'
          ? 'mg-daemon:rejected'
          : 'mg-daemon:needs-info';

        let comment = `**Triage: ${triageResult.outcome}**\n\n${triageResult.reason}`;
        if (triageResult.questions && triageResult.questions.length > 0) {
          comment += '\n\n**Questions:**\n' + triageResult.questions.map(q => `- ${q}`).join('\n');
        }

        await deps.provider.addComment(ticket.id, comment);
        await deps.provider.addLabel(ticket.id, label);
      } catch {
        // Best-effort — don't fail the pipeline on comment/label errors
      }
    }

    deps.tracker.markFailed(ticket.id, `Triage: ${triageResult.outcome} — ${triageResult.reason}`);
    return {
      ticketId: ticket.id,
      triageResult,
      planned: [],
      executed: [],
      success: false,
      error: `Triage: ${triageResult.outcome} — ${triageResult.reason}`,
    };
  }

  // Step 1: Transition to In Progress (write operation — skip in dry-run)
  if (!dryRun) {
    try {
      await deps.provider.transitionStatus(ticket.id, 'in_progress');
    } catch {
      // Log but don't fail — some trackers have strict workflow rules
    }
  }

  // Step 2: Plan workstreams (read-only Claude call — always runs)
  let planned: WorkstreamPlan[];
  try {
    planned = await planFn(ticket, { timeout, dryRun }, passthrough);
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    deps.tracker.markFailed(ticket.id, error);
    return {
      ticketId: ticket.id,
      triageResult,
      planned: [],
      executed: [],
      success: false,
      error,
    };
  }

  // Empty plan — nothing to do
  if (planned.length === 0) {
    return {
      ticketId: ticket.id,
      triageResult,
      planned: [],
      executed: [],
      success: false,
      error: 'Planning produced no workstreams',
    };
  }

  // Dry-run: return the plan without executing any write operations
  if (dryRun) {
    return { ticketId: ticket.id, triageResult, planned, executed: [], success: true };
  }

  // Step 3: Create subtasks for each workstream
  for (const ws of planned) {
    await deps.provider.createSubtask(ticket.id, {
      title: ws.name,
      description: ws.acceptanceCriteria,
      parentId: ticket.id,
      labels: ticket.labels,
    });
  }

  // Step 4: Create worktree
  const { worktreePath, branchName } = createWorktreeFn(ticket.id, ticket.title, baseBranch);

  let executed: ExecutionResult[] = [];
  let prUrl: string | undefined;

  try {
    // Step 5: Execute workstreams
    for (const ws of planned) {
      const result = await executeFn(ws, ticket, worktreePath, { timeout }, passthrough);
      executed.push(result);
    }

    // Step 5b: Merge latest main into worktree before committing
    const gitOpts = { cwd: worktreePath, encoding: 'utf-8' as const };

    spawnSync('git', ['fetch', 'origin', baseBranch], gitOpts);
    const mergeResult = spawnSync('git', ['merge', `origin/${baseBranch}`, '--no-edit'], gitOpts);
    if (mergeResult.status !== 0) {
      // Merge conflict — abort and report failure
      spawnSync('git', ['merge', '--abort'], gitOpts);
      deps.tracker.markFailed(ticket.id, 'Merge conflict with main');
      return { ticketId: ticket.id, triageResult, planned, executed, success: false, error: 'Merge conflict with main' };
    }

    // Step 5c: Stage all changes
    spawnSync('git', ['add', '-A'], gitOpts);

    // Check if there are changes to commit
    const diffResult = spawnSync('git', ['diff', '--cached', '--quiet'], gitOpts);
    if (diffResult.status === 0) {
      // No changes — execution produced nothing
      deps.tracker.markFailed(ticket.id, 'No code changes produced');
      return { ticketId: ticket.id, triageResult, planned, executed, success: false, error: 'No code changes produced' };
    }

    // Step 5d: Run quality gates (tests + build) before committing
    const npmOpts = { cwd: `${worktreePath}/daemon`, encoding: 'utf-8' as const, timeout: 120_000 };

    const testResult = spawnSync('npx', ['vitest', 'run'], { ...npmOpts, env: { ...process.env, VOLTA_HOME: `${process.env.HOME}/.volta`, PATH: `${process.env.HOME}/.volta/bin:${process.env.PATH}` } });
    if (testResult.status !== 0) {
      // Tests failed — still commit and push so the PR shows what was attempted, but mark as draft with test failures
      const testOutput = testResult.stdout?.substring(testResult.stdout.length - 500) ?? '';
      executed.push({ workstream: 'quality-gate', success: false, output: testOutput, error: 'Tests failed', durationMs: 0 });
    }

    const buildResult = spawnSync('npx', ['tsc'], { ...npmOpts, env: { ...process.env, VOLTA_HOME: `${process.env.HOME}/.volta`, PATH: `${process.env.HOME}/.volta/bin:${process.env.PATH}` } });
    if (buildResult.status !== 0) {
      executed.push({ workstream: 'quality-gate', success: false, output: buildResult.stderr ?? '', error: 'Build failed', durationMs: 0 });
    }

    // Step 5e: Commit and push (even if tests fail — PR will show failures)
    spawnSync('git', ['commit', '-m', `feat(${ticket.id}): ${ticket.title}\n\nWorkstreams: ${planned.map(ws => ws.name).join(', ')}\n\nCo-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>`], gitOpts);
    spawnSync('git', ['push', '-u', 'origin', branchName], gitOpts);

    // Step 6: Create draft PR
    const prBody = buildPRDescription(ticket, planned, executed);
    const ticketData = {
      key: ticket.id,
      summary: ticket.title,
      description: prBody,
      priority: ticket.priority,
      labels: ticket.labels,
      url: ticket.url,
    };
    const prResult = createPRFn(ticketData, branchName, deps.config);

    if (prResult.success && prResult.prUrl) {
      prUrl = prResult.prUrl;

      // Step 7: Link PR to ticket
      await deps.provider.linkPR(ticket.id, prUrl);

      // Step 8: Transition to In Review
      try {
        await deps.provider.transitionStatus(ticket.id, 'in_review');
      } catch {
        // Log but don't fail — some trackers have strict workflow rules
      }

      // Update tracker
      deps.tracker.markComplete(ticket.id, prUrl);
    } else {
      deps.tracker.markFailed(ticket.id, prResult.error ?? 'PR creation failed');
    }
  } finally {
    // Step 9: Always clean up worktree
    try {
      removeWorktreeFn(worktreePath);
    } catch {
      // Best-effort cleanup — do not let removal failure mask pipeline result
    }
  }

  return {
    ticketId: ticket.id,
    triageResult,
    planned,
    executed,
    prUrl,
    success: prUrl !== undefined,
  };
}

/**
 * Main poll loop: poll for tickets, process each one.
 * Respects concurrency and delay settings.
 */
export async function runPollCycle(deps: OrchestratorConfig): Promise<PipelineResult[]> {
  // Emergency stop check — if .mg-daemon/STOP exists, halt immediately
  if (shouldStop()) {
    return [];
  }

  // Disk space guard — refuse to process if below 5 GB free
  if (!hasSufficientDiskSpace()) {
    return [];
  }

  const tickets = await deps.provider.poll();
  const processedKeys = deps.tracker.getProcessedTickets();

  const pending = tickets.filter((t) => !processedKeys.includes(t.id));

  const limiter = new ConcurrencyLimiter({
    maxConcurrent: deps.config.orchestration?.concurrency ?? 1,
    delayBetweenTicketsMs: deps.config.orchestration?.delayBetweenTicketsMs ?? 5000,
  });

  const results: PipelineResult[] = [];
  const promises = pending.map(async (ticket) => {
    await limiter.acquire();
    try {
      const result = await processTicket(ticket, deps);
      results.push(result);
    } finally {
      limiter.release();
    }
    await limiter.delay();
  });

  await Promise.all(promises);
  return results;
}
