/**
 * Unit Tests: Context Compression for Document Deliverables
 *
 * Issue #4: Compress large deliverable documents (PRD, Technical Design, Brand Kit)
 * into artifact bundles for downstream agents.
 *
 * The compression behavior must be documented in one of:
 *   - src/framework/shared/development-workflow.md  (artifact bundle section)
 *   - src/framework/skills/mg-build/SKILL.md        (spawn pattern / context section)
 *
 * Tests are ordered misuse-first per CAD TDD protocol:
 *   1. MISUSE   — prohibited patterns (lossy LLM summarization, raw full-doc injection)
 *   2. BOUNDARY — per-document-type compression specs are distinct from each other
 *   3. GOLDEN   — all three document types covered, budgets stated, bundle format referenced
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

const SRC_SHARED = path.resolve(__dirname, '../../src/framework/shared');
const SRC_SKILLS = path.resolve(__dirname, '../../src/framework/skills');

const WORKFLOW   = path.join(SRC_SHARED, 'development-workflow.md');
const MG_BUILD   = path.join(SRC_SKILLS, 'mg-build', 'SKILL.md');

// ---------------------------------------------------------------------------
// Helper — read both candidate files and join them so a single regex covers
// either location. Tests that care about a specific file read it directly.
// ---------------------------------------------------------------------------

function compressionSurface(): string {
  const workflow  = fs.existsSync(WORKFLOW)  ? fs.readFileSync(WORKFLOW,  'utf-8') : '';
  const mgBuild   = fs.existsSync(MG_BUILD)  ? fs.readFileSync(MG_BUILD,  'utf-8') : '';
  return workflow + '\n' + mgBuild;
}

// ============================================================================
// MISUSE CASES — tested first
// What must NOT be present / what is explicitly prohibited
// ============================================================================

describe('Misuse: LLM-based / lossy summarization of acceptance criteria is not allowed', () => {
  it('must not describe acceptance criteria as "summarized" or "condensed" by the model', () => {
    // Given: a task agent receives a compressed PRD
    // When: the compression spec is followed
    // Then: acceptance criteria are never summarized — they are extracted verbatim
    //
    // Rationale: lossy AC summarization is the #1 way a spec quietly loses requirements.
    // The protocol must forbid it explicitly so agents can't justify it.
    const surface = compressionSurface();
    const impliesLossySummary =
      /acceptance.{0,30}(summarize|condense|paraphrase|rewrite|shorten)/i.test(surface);
    expect(impliesLossySummary).toBe(false);
  });

  it('must not describe acceptance criteria as produced by the model autonomously', () => {
    // Acceptance criteria must come from the PRD — not be generated by mg-build.
    // Any phrasing like "generate acceptance criteria from the PRD" is a misuse.
    const surface = compressionSurface();
    const impliesGeneratedAC =
      /generate.{0,30}acceptance.criteria|acceptance.criteria.{0,30}generated.by/i.test(surface);
    expect(impliesGeneratedAC).toBe(false);
  });

  it('must not describe passing the raw full PRD document directly into a task agent prompt', () => {
    // Given: a PRD exists at docs/prd-feature.md
    // When: mg-build builds an artifact bundle for dev or qa
    // Then: the full PRD must NOT be injected wholesale — only the compressed summary
    //
    // Rationale: full documents blow context budgets and add noise. The protocol must
    // make clear that the orchestrator reads the full doc and passes a compressed form.
    const surface = compressionSurface();

    // "pass the full PRD" / "inject full document" / "include entire PRD" patterns
    const impliesFullDocInjection =
      /pass.{0,20}full.{0,20}(prd|document|technical.design)|inject.{0,20}(full|entire|complete).{0,20}(prd|document)/i.test(surface);
    expect(impliesFullDocInjection).toBe(false);
  });

  it('must not describe a single generic compression strategy applied to all document types equally', () => {
    // Each document type has a different payload: PRD extracts AC + constraints,
    // Technical Design extracts selected approach + risks, Brand Kit extracts tokens.
    // A single catch-all compression rule cannot honor these distinctions.
    //
    // We check that the spec does NOT use wording like "compress all documents the same way"
    // or a single undifferentiated bullet that covers PRD, Technical Design, AND Brand Kit
    // in one sentence with no per-type detail.
    const surface = compressionSurface();
    const undifferentiatedCompression =
      /compress.{0,20}(all|any)\s+documents?\s+(the\s+same|equally|uniformly)/i.test(surface);
    expect(undifferentiatedCompression).toBe(false);
  });
});

// ============================================================================
// BOUNDARY CASES — edge conditions that distinguish correct from almost-correct
// ============================================================================

describe('Boundary: Brand Kit compression spec is distinct from PRD compression spec', () => {
  it('Brand Kit compression must be documented separately from PRD compression', () => {
    // Given: development-workflow.md or mg-build SKILL.md describes document compression
    // When: a reader looks for Brand Kit guidance
    // Then: there must be a distinct entry for Brand Kit — not just PRD/Technical Design
    //
    // A spec that only covers PRD + Technical Design and expects Brand Kit to "follow the same
    // pattern" is a boundary failure — Brand Kit has a different payload (color tokens, font
    // stack) and target agent (design, not dev/qa).
    const surface = compressionSurface();
    expect(surface).toMatch(/brand.?kit/i);
  });

  it('PRD compression and Brand Kit compression must reference different target agents', () => {
    // PRD bundles go to dev and qa; Brand Kit bundles go to design.
    // The spec must not claim Brand Kit goes to dev or qa.
    //
    // This is a boundary test: if the implementation naively lists all three document types
    // under a single "task agents (dev, qa)" heading, it fails this check.
    const surface = compressionSurface();

    // Brand Kit must name "design" agent in its context
    expect(surface).toMatch(/brand.?kit.{0,200}design|design.{0,200}brand.?kit/is);
  });

  it('Technical Design compression spec must be distinct from PRD compression spec', () => {
    // PRD extracts: acceptance criteria, constraints, key decisions.
    // Technical Design extracts: selected approach, risk mitigations.
    // These are not the same payload and must not be documented as identical.
    //
    // A spec that says "extract acceptance criteria from all documents including Technical Design"
    // is incorrect — Technical Design does not have acceptance criteria.
    const surface = compressionSurface();

    // Technical Design must have its own section or bullet
    expect(surface).toMatch(/technical.?design.{0,200}(selected approach|risk.{0,20}mitigat|approach.{0,20}risk)/is);
  });

  it('context budgets must be stated as discrete numbers, not vague terms like "small" or "brief"', () => {
    // Given: the spec documents context budgets for task agents
    // When: a reader needs to know how much to compress
    // Then: budgets must be expressed as token counts (e.g., 8K, 12K) not vague adjectives
    //
    // "Keep it brief" is not a spec. "~8K token budget" is a spec.
    const surface = compressionSurface();

    // Must contain at least one numeric token budget (e.g. 8K, 12K, 8000, 12000)
    expect(surface).toMatch(/\b(8[Kk]|12[Kk]|8[,.]?000|12[,.]?000)\b.*token|\btoken.{0,10}\b(8[Kk]|12[Kk])/i);
  });

  it('PRD compression must not claim to extract fields that do not exist in the PRD template', () => {
    // The PRD template (prd-template.md) has: Problem, Users, Success Criteria, User Stories,
    // Acceptance Criteria, Design Requirements, Business Case.
    // The compression spec must only reference fields that actually exist in that template.
    //
    // A common boundary error: listing "Architecture Decisions" as a PRD compression field —
    // that lives in the Technical Design, not the PRD.
    const surface = compressionSurface();

    // Must NOT claim to extract "architecture decisions" or "implementation plan" from the PRD
    const claimsNonPRDFields =
      /prd.{0,60}(architecture.decision|implementation.plan|selected.approach)/i.test(surface);
    expect(claimsNonPRDFields).toBe(false);
  });
});

describe('Boundary: Orchestrator reads full documents, task agents receive compressed versions', () => {
  it('must state that mg-build (orchestrator) reads the full source document', () => {
    // The orchestrator / mg-build reads the full PRD or Technical Design before compressing.
    // This is the information asymmetry that makes compression safe — the orchestrator has
    // full context; it decides what to forward. The spec must make this explicit.
    const surface = compressionSurface();
    expect(surface).toMatch(
      /orchestrator.{0,80}(read|load|access).{0,40}(full|complete|entire)|mg-build.{0,80}(read|load).{0,40}(full|document)/is
    );
  });

  it('must state that task agents receive a compressed or summarized version, not the full document', () => {
    // The corollary to the above: task agents (dev, qa, design) must be documented as
    // receiving the compressed form, not full documents.
    const surface = compressionSurface();
    expect(surface).toMatch(
      /(task.agent|dev|qa|design).{0,120}(compress|summarize|extract|compact|bundle)/is
    );
  });
});

// ============================================================================
// GOLDEN PATH — the happy path: all three document types covered correctly
// ============================================================================

describe('Golden: PRD compression described for dev and qa artifact bundles', () => {
  it('PRD compression is documented somewhere in development-workflow.md or mg-build SKILL.md', () => {
    // Given: development-workflow.md or mg-build SKILL.md has been updated for issue #4
    // When: the compression section is read
    // Then: PRD compression behavior is described
    const surface = compressionSurface();
    expect(surface).toMatch(/prd.{0,200}compress|compress.{0,200}prd/is);
  });

  it('PRD compression preserves acceptance criteria', () => {
    // Acceptance criteria must survive PRD compression intact.
    // This is the core lossless requirement for PRD → dev/qa bundles.
    const surface = compressionSurface();
    expect(surface).toMatch(/prd.{0,300}acceptance.criteria|acceptance.criteria.{0,300}prd/is);
  });

  it('PRD compression preserves constraints', () => {
    // Constraints (technical, timeline, budget) must be present in the compressed bundle.
    // A bundle without constraints leads to dev implementations that violate unstated limits.
    const surface = compressionSurface();
    expect(surface).toMatch(/prd.{0,300}constraint|constraint.{0,300}prd/is);
  });

  it('PRD compression preserves key decisions', () => {
    // Key product decisions recorded in the PRD must be preserved in the compressed output.
    const surface = compressionSurface();
    expect(surface).toMatch(/prd.{0,300}(key.decision|decision)|decision.{0,300}prd/is);
  });

  it('PRD compressed output targets the dev and/or qa agent bundles', () => {
    // The PRD compression output must be described as going to dev and/or qa — not to
    // staff-engineer or design (those agents use different document types).
    const surface = compressionSurface();
    expect(surface).toMatch(/prd.{0,300}(dev|qa)|( dev| qa).{0,300}prd/is);
  });
});

describe('Golden: Technical Design compression described for dev and staff-engineer bundles', () => {
  it('Technical Design compression is documented', () => {
    const surface = compressionSurface();
    expect(surface).toMatch(/technical.?design.{0,200}compress|compress.{0,200}technical.?design/is);
  });

  it('Technical Design compression preserves the selected approach', () => {
    // "Selected Approach" is the primary output of a Technical Design and the most critical
    // field for a dev implementing the work. It must survive compression.
    const surface = compressionSurface();
    expect(surface).toMatch(/technical.?design.{0,400}selected.approach|selected.approach.{0,200}technical.?design/is);
  });

  it('Technical Design compression preserves risk mitigations', () => {
    // Risk mitigations from the Technical Design tell dev what to watch for.
    // A bundle that omits risks leads to implementations that ignore known failure modes.
    const surface = compressionSurface();
    expect(surface).toMatch(/technical.?design.{0,400}risk.{0,20}mitigat|risk.mitigat.{0,200}technical.?design/is);
  });

  it('Technical Design compressed output targets dev and/or staff-engineer bundles', () => {
    // Staff-engineer reviews architecture — they need the Technical Design compressed summary.
    // Dev implements against it. Design and QA do not receive Technical Design bundles.
    const surface = compressionSurface();
    expect(surface).toMatch(/technical.?design.{0,300}(dev|staff.engineer)|( dev|staff.engineer).{0,300}technical.?design/is);
  });
});

describe('Golden: Brand Kit compression described for design agent bundles', () => {
  it('Brand Kit compression is documented', () => {
    const surface = compressionSurface();
    expect(surface).toMatch(/brand.?kit.{0,200}compress|compress.{0,200}brand.?kit/is);
  });

  it('Brand Kit compression preserves color token values', () => {
    // The design agent needs color values (hex codes or semantic names) to produce
    // spec-compliant wireframes. These must be present in the compressed token bundle.
    const surface = compressionSurface();
    expect(surface).toMatch(/brand.?kit.{0,400}(color.token|color.value|hex)/is);
  });

  it('Brand Kit compression preserves the font stack', () => {
    // Typography (font stack) is a constitutional design constraint.
    // A compressed Brand Kit that omits the font stack yields wireframes with wrong fonts.
    const surface = compressionSurface();
    expect(surface).toMatch(/brand.?kit.{0,400}(font.stack|font.famil|typeface|typography)/is);
  });

  it('Brand Kit compressed output targets the design agent bundle', () => {
    // Brand Kit tokens go to the design agent, not dev or qa.
    const surface = compressionSurface();
    expect(surface).toMatch(/brand.?kit.{0,200}design.?agent|design.?agent.{0,200}brand.?kit/is);
  });
});

describe('Golden: Context budgets are documented for task agents', () => {
  it('QA agent context budget (~8K tokens) is documented', () => {
    // Already exists in development-workflow.md. This test verifies it is not removed
    // during the compression feature implementation and is still present post-update.
    const surface = compressionSurface();
    expect(surface).toMatch(/qa.{0,30}8[Kk]|8[Kk].{0,30}qa/i);
  });

  it('Dev agent context budget (~12K tokens) is documented', () => {
    // Already exists in development-workflow.md. Same preservation check.
    const surface = compressionSurface();
    expect(surface).toMatch(/dev.{0,30}12[Kk]|12[Kk].{0,30}dev/i);
  });

  it('context budgets are referenced in the same section that describes compression', () => {
    // The compression spec must co-locate or explicitly reference context budgets.
    // If they are in separate, unlinked sections an agent reading one section may not see
    // the other and produce oversized bundles.
    //
    // We check that the two concepts appear within 800 characters of each other.
    const surface = compressionSurface();
    const compressIdx = surface.search(/compress/i);
    const budgetIdx   = surface.search(/\b(8[Kk]|12[Kk]).{0,10}token|\btoken.{0,10}(8[Kk]|12[Kk])/i);

    // Both must exist first
    expect(compressIdx).toBeGreaterThan(-1);
    expect(budgetIdx).toBeGreaterThan(-1);

    // Must be within 3000 characters of each other in the combined surface
    expect(Math.abs(compressIdx - budgetIdx)).toBeLessThan(3000);
  });
});

describe('Golden: Artifact bundle format compatibility', () => {
  it('document compression is described in terms of INPUTS / GATE / CONSTRAINTS bundle fields', () => {
    // The existing artifact bundle format uses INPUTS, GATE, and CONSTRAINTS.
    // Compressed document content must be described as populating one of these fields —
    // it cannot invent new top-level bundle keys without a corresponding spec update.
    const surface = compressionSurface();
    expect(surface).toMatch(/\bINPUTS\b|\bGATE\b|\bCONSTRAINTS\b/);
  });

  it('compressed PRD content is described as populating the INPUTS or CONSTRAINTS field of the bundle', () => {
    // INPUTS is the natural home for compressed document context.
    // CONSTRAINTS is a valid alternative for requirement-type content from the PRD.
    // It must not describe PRD content as going to GATE (that is the workstream success criterion).
    const surface = compressionSurface();
    expect(surface).toMatch(/(prd|document).{0,200}(INPUTS|CONSTRAINTS)|(INPUTS|CONSTRAINTS).{0,200}(prd|document)/is);
  });

  it('does not invent new top-level bundle fields (e.g. DOCUMENTS or ATTACHMENTS) without documenting them', () => {
    // If the implementation adds a new DOCUMENTS field to the bundle format, it must be
    // described in the artifact bundle spec. An undocumented new field is a misuse of the format.
    //
    // We verify that any mention of a new field name is accompanied by a definition.
    const surface = compressionSurface();

    // If DOCUMENTS or ATTACHMENTS appears as a field, it must be followed by a colon (definition)
    // or preceded by text that defines it — not just referenced in passing.
    const hasUndocumentedDocumentsField =
      /\bDOCUMENTS\b(?!.*:|\s*—|\s*\()/i.test(surface) ||
      /\bATTACHMENTS\b(?!.*:|\s*—|\s*\()/i.test(surface);
    expect(hasUndocumentedDocumentsField).toBe(false);
  });
});
